import type { Metadata } from "next";
import "./globals.css";

// Offline-first: the `--font-geist-sans` / `--font-geist-mono` CSS variables are defined as
// system-font stacks in globals.css. This removes the build-time network dependency that
// `next/font/google` (Geist / Geist Mono) introduced by fetching fonts.googleapis.com during
// `next build`. Visual tradeoff: system fonts instead of Geist; variable names and layout preserved.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
