export enum ErrorCode {
  INVALID_METRIC = "INVALID_METRIC",
  INVALID_CONFIG = "INVALID_CONFIG",
  INVALID_THRESHOLD = "INVALID_THRESHOLD",
  CONTRACT_VIOLATION = "CONTRACT_VIOLATION",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
